#!/bin/bash

set -e

# Default settings
output_folder=
url=
library_version=
library_name=

# usage
#
# Shows the help-message
#
# Arguments:
# (none)
function usage(){
	cat <<END
TODO
END
}

for (( i=1; i<=$#; i++ ))
do
	arg_i=${@:$i:1}   # get argument i
	arg_j=${@:$i+1:1} # get argument i+1
	case $arg_i in
	-h|--help)
		usage
		exit 0
		;;
	-o)
		output_folder=${arg_j#*./}
		shift
		;;
	--output=*)
		# split at = char and remove the shortest match from beginning
		output_folder=${arg_i#*=}
		# remove / at end (if none exists, nothing happens)
		output_folder=${output_folder%/}
		;;
	-u)
		url=$arg_j
		shift
		;;
	--url=http://*)
		# split at = char and remove the shortest match from beginning
		url=${arg_i#*=}
		shift
		;;
	-l)
		library_name=$arg_j
		shift
		;;
	--library=*)
		# split at = char and remove the shortest match from beginning
		library_name=${arg_i#*=}
		shift
		;;
	-v)
		library_version=$arg_j
		shift
		;;
	--version=*)
		# split at = char and remove the shortest match from beginning
		library_version=${arg_i#*=}
		shift
		;;
	*)
		echo "Unknown argument number $i: '$arg_i'"
		;;
	esac
done


