#!/bin/bash

set -e

# Default settings
output_folder=
url=
library_version=
library_name=
library_name_raw=
operatoin=

# usage
#
# Shows the help-message.
#
# Arguments: 
#   (none)
#
# Variables:
#   (none)
function usage(){
	cat <<END
TODO
END
}

# parse_conf_file
#
# Parses the conf file and saves the entries in the global variables.
# The config file "pic.conf" should exist.
#
# Arguments:
#   (none)
#
# Variables:
#   url
#   output_folder
function parse_conf_file(){
	while IFS= read -r line
	do
		key=${line%%\:*}
		value=${line#*:}

		case $key in
		url)
			url=$value
			# remove / at end (if none exists, nothing happens)
			url=${url%/}
			;;
		output_folder)
			output_folder=$value
			# remove / at end (if none exists, nothing happens)
			output_folder=${output_folder%/}
			;;
		\#*)
			# Lines with a "#" at the beginning are comments
			;;
		+)
			echo "Unknown config entry '$line'"
			;;
		esac
	done < "./pic.conf"
}

# parse_install_args
#
# Parses the args passed to the install operation.
#
# Arguments:
#   @
#
# Variables:
#   library_name
#   library_version
function parse_install_args(){
	# Gets the library specification (including version) 

	for (( i=2; i<=$#; i++ ))
	do
		arg_i=${@:$i:1}   # get argument i
		arg_j=${@:$i+1:1} # get argument i+1

		echo $arg_i

		case $arg_i in
		-h|--help)
			usage
			exit 0
			;;
		-o)
			output_folder=${arg_j#*./}
			# remove / at end (if none exists, nothing happens)
			output_folder=${output_folder%/}
			;;
		--output=*)
			# split at = char and remove the shortest match from beginning
			output_folder=${arg_i#*=}
			# remove / at end (if none exists, nothing happens)
			output_folder=${output_folder%/}
			;;
		-u)
			url=$arg_j
			# remove / at end (if none exists, nothing happens)
			url=${url%/}
			;;
		--url=*)
			# split at = char and remove the shortest match from beginning
			url=${arg_i#*=}
			# remove / at end (if none exists, nothing happens)
			url=${url%/}
			;;
		*)
			library_name_raw=$arg_i
			break
			;;
		esac
	done

	# TODO handle empty library_name_raw

	library_name=${library_name_raw%%_*}
	library_version=${library_name_raw#*_}
}

# install
#
# Installs the library specified by the global variables
#
# Arguments:
# (none)
#
# Variables:
# (none)
function install(){
	if [ ! -d "$output_folder" ]
	then
		mkdir $output_folder
	fi
	meta_file="$output_folder/meta_$library_name_raw"
	library_ext=

	echo "Start installing..."

	# Get meta file from server
	response=$(curl --write-out %{http_code} --silent --output $meta_file "$url/$library_name_raw/meta")

	if [ "$response" -ne 200 ]
	then
		echo "Download meta file for $library_name in version $library_version failed"
		echo "HTTP status code: $response"
		exit 1
	fi

	# TODO get meta file and get 'ext' value
	while IFS= read -r line
	do
		key=${line%%\:*}
		value=${line#*:}

		case $key in
		ext)
			library_ext=$value
			;;
		\#*)
			# Lines with a "#" at the beginning are comments
			;;
		+)
			echo "Unknown meta entry '$line'"
			;;
		esac
	done < $meta_file
	
	echo "Library $library_name_raw has file extension '.$library_ext'"

	# TODO parse dependencies
	# TODO check if every dependency exists
	# TODO download dependencies first
	# TODO check if file exists
	# TODO download actual library
}

# To overwrite configs made in the "pic.conf", w parse before(!) reading the CLI-arguments
echo "Begin reading config"
parse_conf_file
echo "Finished reading config"

case ${@:1:1} in
-h|--help)
	usage
	exit 0
	;;
install)
	parse_install_args $@
	operation=install
	;;
remove)
	operatoin=remove
	;;
*)
	echo ""
	echo "Unknown operation '$operation'."
	echo "Use '-h' or '--help' for more information."
	exit 1
	;;
esac

echo ""
echo "Using the following configuration:"
echo ""
echo "url             : $url"
echo "output folder   : $output_folder"
echo "library name    : $library_name"
echo "library version : $library_version"
echo "operation       : $operation" 

# TODO check operation and start parsing, etc.

case $operation in
install)
	install
	;;
remove)
	# TODO call parse_remove_args function
	# TODO call remove function
	;;
esac
